# Generated by Django 4.2.13 on 2024-06-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_course_code'),
        ('teacher', '0004_teachercourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='teachers', through='teacher.TeacherCourses', to='school.course'),
        ),
    ]
