# Generated by Django 4.2.13 on 2024-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_unavailabletimeonetime_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailabletimeonetime',
            name='code',
            field=models.CharField(default='paijjfisajg', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unavailabletimeregular',
            name='code',
            field=models.CharField(default='aisdjfjap', max_length=12),
            preserve_default=False,
        ),
    ]
