# Generated by Django 4.2.13 on 2024-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_unavailabletimeonetime_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailabletimeonetime',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='unavailabletimeregular',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
