# Generated by Django 4.2.13 on 2024-11-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_makeuplesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MakeUpLesson',
        ),
    ]
