# Generated by Django 4.2.13 on 2024-11-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_delete_makeuplesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailabletimeonetime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='unavailabletimeonetime',
            name='start',
        ),
        migrations.RemoveField(
            model_name='unavailabletimeonetime',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='unavailabletimeregular',
            name='start',
        ),
        migrations.RemoveField(
            model_name='unavailabletimeregular',
            name='stop',
        ),
    ]
