# Generated by Django 4.2.13 on 2024-07-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='apsdf', max_length=255),
            preserve_default=False,
        ),
    ]
