# Generated by Django 4.2.13 on 2024-08-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_recieve_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recieve_notification',
        ),
    ]
