# Generated by Django 4.2.13 on 2024-11-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_google_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_credentials',
        ),
        migrations.AddField(
            model_name='user',
            name='gc_client_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gc_client_secret',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gc_refreshtoken',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gc_scopes',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gc_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gc_token_uri',
            field=models.CharField(blank=True, null=True),
        ),
    ]
