# Generated by Django 4.2.13 on 2024-11-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_user_google_credentials_user_gc_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gc_linked',
            field=models.BooleanField(default=False),
        ),
    ]
