# Generated by Django 4.2.13 on 2024-11-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_gc_linked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gc_client_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gc_client_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gc_linked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gc_refreshtoken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gc_scopes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gc_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gc_token_uri',
        ),
        migrations.AddField(
            model_name='user',
            name='google_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
