# Generated by Django 4.2.13 on 2024-11-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_user_gc_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_calendar_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
