# Generated by Django 5.0.4 on 2024-06-04 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('no_exp', models.BooleanField()),
                ('exp_range', models.IntegerField()),
                ('duration', models.IntegerField(default=60)),
                ('number_of_lessons', models.IntegerField(default=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
