# Generated by Django 4.2.13 on 2024-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_school_start_school_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='lorem ipsum', max_length=300),
            preserve_default=False,
        ),
    ]
