# Generated by Django 4.2.13 on 2024-06-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
