# Generated by Django 4.2.13 on 2024-06-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_lesson_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='finised_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
