# Generated by Django 4.2.13 on 2024-06-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_courseregistration_finised_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uuid',
        ),
    ]
