# Generated by Django 4.2.13 on 2024-06-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='code',
            field=models.CharField(default=12, max_length=12),
            preserve_default=False,
        ),
    ]
