# Generated by Django 4.2.13 on 2024-06-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_lesson_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('SCH', 'Scheduled'), ('COM', 'Completed'), ('CAN', 'Canceled'), ('FIN', 'Finished'), ('MIS', 'Missed')], default='SCH', max_length=3),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
