# Generated by Django 4.2.13 on 2024-06-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_lesson_status_alter_lesson_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='attended',
        ),
    ]
