# Generated by Django 4.2.13 on 2024-06-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_lesson_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='confirmed',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('SCH', 'Scheduled'), ('CON', 'Confirmed'), ('COM', 'Completed'), ('CAN', 'Canceled'), ('FIN', 'Finished'), ('MIS', 'Missed')], default='SCH', max_length=3),
        ),
    ]
