# Generated by Django 4.2.13 on 2024-06-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_lesson_confirmed_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('CON', 'Confirmed'), ('COM', 'Completed'), ('CAN', 'Canceled'), ('FIN', 'Finished'), ('MIS', 'Missed')], default='PEN', max_length=3),
        ),
    ]
