# Generated by Django 4.2.13 on 2024-06-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
