# Generated by Django 4.2.13 on 2024-06-22 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_lesson_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='student.courseregistration'),
        ),
    ]
