# Generated by Django 4.2.13 on 2024-06-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_lesson_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='favorite',
            new_name='student_favorite',
        ),
    ]
