# Generated by Django 4.2.13 on 2024-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_courseregistration_teacher_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
