# Generated by Django 4.2.13 on 2024-08-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('PENTE', 'PendingTeacher'), ('PENST', 'PendingStudent'), ('CON', 'Confirmed'), ('COM', 'Completed'), ('CAN', 'Canceled'), ('MIS', 'Missed')], default='PENTE', max_length=5),
        ),
    ]
