# Generated by Django 4.2.13 on 2024-09-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_course_short_description'),
        ('teacher', '0009_alter_unavailabletimeonetime_code_and_more'),
        ('student', '0019_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='school.course'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
