# Generated by Django 4.2.13 on 2024-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_courseregistration_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
