# Generated by Django 4.2.13 on 2024-11-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_rename_makeuplesson_guestlesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestlesson',
            old_name='booked_datetime',
            new_name='datetime',
        ),
    ]
