# Generated by Django 4.2.13 on 2024-11-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_rename_booked_datetime_guestlesson_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteacherrelation',
            name='student_color',
            field=models.CharField(default='C7E7DD', max_length=6),
        ),
        migrations.AddField(
            model_name='studentteacherrelation',
            name='student_first_name',
            field=models.CharField(default='unknown'),
        ),
        migrations.AddField(
            model_name='studentteacherrelation',
            name='student_last_name',
            field=models.CharField(default='unknown'),
        ),
    ]
