# Generated by Django 4.2.13 on 2024-11-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_guestlesson_email_alter_guestlesson_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteacherrelation',
            name='student_color',
            field=models.CharField(default='C5E5DB', max_length=6),
        ),
    ]
