# Generated by Django 4.2.13 on 2024-11-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_lesson_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_event_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_event_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
