# Generated by Django 4.2.13 on 2024-11-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_lesson_student_event_id_lesson_teacher_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlesson',
            name='teacher_event_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
