# Generated by Django 4.2.13 on 2024-11-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_guestlesson_teacher_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestlesson',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
